# Configuration

mission: Cloud

server:
    port:4000

groundstation0:
    port:4004

groundstation1:
    port:4005

groundstation2:
    port:4006

master:
    port:8000

worker1:
    port:8008

worker2:
    port:8009
