# Configuration

missions:
    - SENSE
    - STORE
    - PROCESS
    - DOWNLINK

server:
    address: localhost
    port: 4000

groundstation:
    address: localhost
    port: 4004

master:
    address: localhost
    port: 8000

csserver:
    address: localhost
    port: 8008
    
groundstation0:
    address: localhost
    port: 4004

groundstation1:
    address: localhost
    port: 4005

groundstation2:
    address: localhost
    port: 4006
    
worker0:
    address: localhost
    port: 8008
    
worker1:
    address: localhost
    port: 8008

worker2:
    address: localhost
    port: 8009
