mission: Torrent

GroundStation:
    network:
        latency: 217361
        speed: 3231

Server:
    a: 23
    b: 33
            
CubeSat:
    processor:
	    speed:	1000000000
	    mips:	1000000000
	    power:	0

    memory:
	    capacity:   32000000000
	    bandwidth:  10000000
	    power:      0

    battery:
        capacity:
        charge_rate:

    nic:
        speed: 10000000
        power: 0

    transciever:
        speed: 9600
        power: 0

    location:
        x:  0
        y:  0

    tle: none
